---
title: "Democratie en onderwijs"
subtitle: "Een klein boek over een grote filosoof"
author: Harrie Jonkman
dedication: |
  Voor iedereen
publishing-info: |
  Zuideinde 387e \
  1035PE Amsterdam \
  Nederland

  <www.harriejonkman.nl/>

  0031-6-34738591
format:
  fiction-typst: default
---

## Inleiding

Op dit moment werk ik aan een studie over Democratie en Onderwijs. Ik recenseer interessante recente boeken die hierover gaan, de ene keer is het een bijdrage over democratie, de andere keer is het een bijdrage over onderwijs. Tegelijkertijd bestudeer ik het werk John Dewey (1859-1952), de grote Amsrikaanse filosoof die uitgebreid hierover heeft geschreven. In later stadium zal ik de eigentijdse en historische bijdragen naar elkaar toeschrijven. 

Hier vind je de vier laatste eigentijdse bijdragen die ik recent schreef en die je terug kunt vinden op mijn [Democratie en Onderwijs-blog](https://democratieenonderwijs.netlify.app) hierover. Deze bijdragen heb ik gebruikt om een eerste opzet te maken voor een boek dat met `Quarto` en `Typst` kan worden gemaakt.


## De goede samenleving
\
\
*Vrijheid voor de wolven betekende vaak dood voor de schapen.*\
- Isaiah Berlin
\
\
Joseph Stiglitz is een Amerikaanse econoom die in 2001 de Nobel Prijs won voor een theorie over hoe deelnemers aan de markt met ongelijke informatie om kunnen gaan. Hij werkte in de negentiger jaren voor de regering Clinton, was daarna de hoofdeconoom van de Wereldbank en is tegenwoordig hoogleraar economie aan de Columbia Universiteit in New York. Hij hield zich bezig met klimaatverandering en de relatie met economische ontwikkelingen. Met Amartya Sen zocht hij naar nieuwe economische meetsystemen die meer zeggen dan het Bruto Nationaal Product. In talloze boeken schreef hij over de globalisering, monopolisering, toenemende ongelijkheid en afnemende economische groei en mogelijkheden voor mensen. Hem interesseert de vraag welke alternatieve economische systemen en maatregelen passen bij een samenleving die het beste met mensen voor heeft en welke weg daartoe is er af te leggen. Stiglitz is bij dat alles kritisch over het neoliberale karakter van de economie in de westerse wereld gedurende de afgelopen halve eeuw, in zijn nieuwe boek The Road to Freedom. Economics and the Good Society ook weer. 
\
\
Vrijheid speelt in dat nieuwe boek een centrale rol. Stiglitz weet dat over de betekenis ervan heel verschillend gedacht wordt. Hij stelt vast dat sinds Reagan en Bush het begrip vrijheid niet zozeer meer moreel maar economisch is ingevuld en dat het nu vooral gaat om de belangen van de vrije markt en de banken. De diepere betekenis van het begrip en de relatie met universele welzijn van de mensen zijn we met het neoliberalisme uit het oog verloren. Dat is geen nieuwe constatering en hij is ook niet de enige die het debat over economie en samenleving wil verbreden. Hij doet dat door in dit boek te laten zien hoe het neoliberale denken eruit ziet en wat de consequenties ervan voor vrijheid zijn, welke economische (in de eerste plaats), politieke en sociale organisatie er nodig om de vrijheid van de meeste mensen te garanderen, welke regels horen daarbij en wat de consequenties daarvan zijn. In 1944 schreef Hayek het boek *The Road to Serfdom*, de weg naar een samenleving waarin individuen ondergeschikt gemaakt zijn aan de staat. Het boek wordt het ‘rode’ boekje voor de neoliberalen die het vanaf 1980 voor het zeggen krijgen. Tegenover dat neoliberalisme zet Stiglits zijn *The Road to Freedom*, zijn kijk op de goede samenleving, over vrijheid en democratie, over de economie die daarbij hoort en een routekaart om daar te komen.    

In de zeventiger jaren ondermijnen de oliecrisis en de toenemende inflatie het vertrouwen in het economische arrangement zoals we dat op tot dat moment langere tijd gekend hebben. Het zijn Ronald Reagan en Margaret Thatcher die vooropgaan in de strijd om economisch hervorming en daarbij teruggrijpen op het neoliberale denkwerk van Hayek en Friedman. De nadruk wordt gelegd op deregulering, liberalisering en economische groei, heilige geloof in de markt wordt een religie en het probleem is de overheid. Er ontstaat een soort ‘ersatz capitalism’ waarin verliezen worden gesocialiseerd en winsten worden geprivatiseerd. De meeste overheden in de wereld adopteren een of andere vorm van neoliberalisme, zoals Stiglitz dat overal van nabij ziet gebeuren. Voor hemzelf is het falen van het neoliberalisme heel zichtbaar. Daarvoor wijst hij naar de enorme ongelijkheden die in de samenlevingen ontstaan, de mogelijkheden die afnemen voor grote groepen in de samenleving, de opkomst van populistische partijen, de maatschappelijke problemen die ontstaan met grote farmaceutische ondernemingen en sigaretten- en voedselbedrijven en de mentale problemen waar mensen mee te maken krijgen. Voor Stiglitz is ook duidellijk dat binnen elk economisch systeem compromissen nodig zijn omdat mensen nu een keer met elkaar verbonden zijn. Anders dan de neo-liberalen willen doen geloven, kan iemands vrijheid nooit in isolatie worden bekeken en heeft die altijd te maken met de vrijheid van een ander. Daarop is het neoliberalisme te bekritiseren omdat het problemen creëert in de wisselwerking tussen economische initiatieven en de gevolgen voor grote groepen in de samenleving, het publieke belangen schade toebrengt, er coöordinatieproblemen in de samenleving ontstaan en het de nadelige gevolgen van pure macht blootlegt.   

Stiglits is voor een economisch en politiek systeem dat niet alleen zorgt voor efficiëntie, opbouw van vermogen en duurzaamheid, maar ook morele waarden hanteert. Een wereld in vrijheid kan niet zonder beperkingen, want een wereld zonder beperkingen wordt een jungle. Ten onrechte wordt tegen vrijheid aangekeken als iets positiefs en regels en dwang als iets negatiefs. Vrijheid en beperkingen horen bij elkaar en alleen zo kunnen we een leefwereld voor de wolven én de schapen creëren. Over de regels en voorschriften en de gevolgen ervan kunnen we nadenken. Ook de economische wetenschap heeft laten zien dat mensen sociaal gedetermineerd zijn. We worden wie we zijn door de mensen om ons heen. Zo bouwen we onze waarden en normen op en ons begrip over de wereld en zo worden individuen, vaak onbewust, gevormd als lid van de gemeenschap. In onze eigen tijd is in dat vormen van individuen een grootse rol weggelegd voor de Big Tech bedrijven en de sociale media platforms. Voor een vrije markt van ideeën kun je je afvragen of de individuen zelf wel rationeel en geïnformeerd genoeg zijn om te bepalen wat goed voor hen is. Die markt is namelijk niet transparant en helemaal betrouwbaar. De onafhankelijke instituten die zijn ontstaan om de waarheid een beetje in toom te houden (onafhankelijke rechtspraak, onderzoeks- en onderwijsinstituten, journalistiek) kunnen soms nauwelijks op tegen de macht en de intimidatie en de kracht van meta-narratieven. Lang waren we bang voor een overheid die alles beheerst, nu lijkt het wel of de private sector die rol overneemt. Belangrijke beslissingen dienen collectief genomen te worden. Het is nodig beter door te krijgen hoe economische, politieke en sociale systemen ons vormen, wie daar het recht en de vrijheid voor heeft en welke regels en voorschriften daarvoor nodig zijn. Dat is geen gemakkelijke zaak vanwege de vrijheid van meningsuiting en vrijheid van pers. Een democratie is gebaat bij regulatie waar vrijheid van de een die van de ander in gevaar brengt.    

Van polarisatie is er tegenwoordig niet alleen sprake binnen landen, ook tussen landen is er sprake van. Stiglitz pleit voor een concreet raamwerk van meer eerlijke en rechtvaardige afspraken en vrijheid dat niet alleen naar de rechten maar ook naar de verantwoordelijkheden kijkt van samenwerkende landen. Ook hier geldt, landen kunnen dan doen wat ze willen als ze maar niet andere landen schaden, als de afspraken rechtvaardig zijn en als bij de economische afspraken ook de sociale kosten worden meegerekend. In zijn boek verdedigt hij een progressief kapitalisme (een verjongde sociaal democratie, noemt hij het ook wel) dat er voor zorgt dat mensen het goed hebben en zij zich veilig voelen en dat vrijheid serieus neemt. Een systeem ook waarin mensen kunnen floreren, een betekenisvol en creatief leven kunnen leiden, met goede gezondheidszorg, onderwijs, en bestaanszekerheid. De goede samenleving die hij voor ogen heeft zorgt ervoor dat macht niet in handen ligt van een kleine groep mensen maar wordt verdeeld. Net zo goed als dat het ervoor zorgt dat de sterke ongelijkheid weer afneemt. Het zorgt voor collectieve actie waar nodig en is zich bewust van de rol ook die economie speelt in het vormen van mensen. De samenleving blijft veranderen. Mensen en instituten moeten zich voortdurend kunnen aanpassen en daarom wordt binnen die goede samenleving leren als een levenslang proces gezien. Daarom ook wordt er publiek geïnvesteerd in kinderen en de toekomst, in onderzoek en de sociale en fysieke infrastructuur. Die goede samenleving heeft een gedecentraliseerde economie nodig want de wereld is te complex om centraal aangestuurd te worden. Er zijn heel veel verschillende soorten instituten nodig en niet alles van de economie hoeft op winst gericht te zijn.  
\
\
Stiglitz is in zijn *The Road to Freedom* op zoek vrijheid en de goede samenleving die ervoor zorgen dat individuen kunnen floreren en groeien en in harmonie met elkaar en de natuur kunnen leven en dat brengt hem bij onderwijs en democratie. De lens waarmee we de wereld zien wordt beïnvloed door de mensen om ons heen. Goed onderwijs helpt ons de krachten die daarin spelen te begrijpen, we worden er coöperatiever en betrouwbaarder door als we beter weten wat nodig is. Tegelijk is het nodig de democratie te verjongen, door beslissingen meer vanuit het perspectief van rechtvaardigheid te nemen. Door ongelijkheid aan te pakken, door geld hierbij een minder belangrijkere rol te geven en beslissingen beter te onderbouwen. *The Road to Freedom* komt behoorlijk rommelig op mij over. Zaken lopen door elkaar heen en iets wat eerder is behandeld, komt later opnieuw aan de orde. Hij had beter de analyse van het neo-liberalisme, zijn eigen concrete voorstellen en zijn lange termijn perspectief uit elkaar kunnen trekken en er een compact boek van kunnen maken. De onderbouwing van rechtvaardigheid en hoe we beslissingen eerlijker kunnen maken, verdiende meer aandacht en ook de rol van informatie daarbij kunnen betrekken (waar hij ooit de Nobelprijs voor ontving). Stiglitz heeft in het boek veel op met het idee van de ‘onpartijdige toeschouwer’ van Adam Smith en de ‘sluier van onwetendheid’ van John Rawls. Daarmee geeft hij een filosofische onderbouwing van de waarden die we met elkaar hebben na te streven, als een betere manier om mensen te vormen. Ik snap wat hij bedoelt, maar het blijft er wat bij hangen. Het had beter gekund en hij had het beter kunnen doen, denk je als je het leest. Maar er blijft nog zoveel van waarde over en uiteindelijk heeft Stiglitz natuurlijk helemaal gelijk als hij zegt dat we soms vergeten dat de economie er is om de samenleving te dienen en niet anders om.	 
\
\
Stiglitz, J.(2024). *The Road to Freedom. Economics and the Good Society*. Dublin: Allen Lane/Penguin Random House UK. 356 pagina’s.


## Een paar richtlijnen voor de toekomst
\
\
*Het bijzonderste wat Amerika aan de geest en de wijsheid van de wereld heeft bijgedragen.*\
- Ralf Waldo Emerson
\
\
Walt Whitman, zo schrijft Jan-Hendrik Bakker in zijn boek *De Kracht van gras. Walt Whitman en onze tijd*, is een van de mensen geweest die Amerika z’n identiteit geeft. Zoals Bob Dylan dat een eeuw later zal doen, zeg maar. Whitman (1819-1892) doet dat met z’n dichtbundel *Leaves of Grass/Grasbladen* dat in 1855 verschijnt en waarin hij in een twaalftal gedichten zijn optimistische vergezicht op de mens, de wereld en de kosmos beschrijft. Er zullen een aantal uitgaven verschijnen en de laatste rondt hij af vlak voor zijn dood. Hij is een selfmade-genie, die op vroege leeftijd moet werken, timmerman is, leraar, journalist, verpleegkundiger en bovenal dichter natuurlijk. Hij is niet alleen van belang voor de Amerikaanse identiteit, hij is ook belangrijk voor de queergemeenschap, inspireert belangrijke dichters en denkers en zijn radicaal humanisme en universeel optimisme geeft mensen hoop op een een betere wereld. Voor de filosoof Bakker is Whitman interessant voor onze tijd waarin de democratie het moeilijk heeft en we niet goed weten welke democratie we nodig hebben. We hebben namelijk met elkaar niet een goed uitgewerkt idee van een gedeelde toekomst. Dat heeft Whitman in de 19e-eeuw wel. Het is goed zijn denken over humaniteit, individualiteit en hoop naar onze tijd te verplaatsen en te kijken naar wat de betekenis van hem nu is.
\
\
Sinds de Renaissance gaat de mens zichzelf als individu zien die deel uitmaakt van de kosmos. Zo ontstaat het idee van vrijheid en ontplooiing. De mens wordt zich bewust van de innerlijke beleving, het dagelijkse leven wordt gezien en de natuur ontdekt. In elk individu zit wel een vonkje goddelijk en zo wordt de wereld ook een mensenwereld die onze liefde verdient en waarin kritiek en verbeelding mogelijk worden. De mens maakt zich los uit het groter verband, maar zet zich ook op de troon en onderwerpt de wereld. De mens krijgt een opdracht omdat humaniteit daarom vraagt. Die opdracht ziet Whitman en voor hem zit het universele in het kleine en het onbeduidende in het moment. Voor hem zit het in de verbinding van het persoonlijke zelf met de zelven van anderen, de zelf die zich kan verplaatsen in de anderen en dat ook van anderen te vragen. Dat individuele, dat dagelijkse en het natuurlijke komen in zijn *Grasbladen* terug. *“Lees deze bladen in de open lucht, elk seizoen, elk jaar van je leven”*.   

Voor Whitman gaat het nog om de verbinding van het individu met de massa. Daarvoor is het nodig je op een goede manier te verhouden tot de anderen. Het gaat hem om vreedzaam samenkomen (concreet en fysiek) van het individu met de anderen op openbare plekken zoals op de veerpont of aan het strand, waarin Whitman jou als ander en lezer op verschillende manieren betrekt en laat zien dat er in massaliteit individualiteit zit (*“Uit het rollen der oceaan, de massa, kwam een druppel zachtjes tot mij”*). Juist nu de individualiteit het zo moeilijk heeft in onze tijd (met z’n eenzaamheid, consumptie/verspilling/verlies sociale cohesie en de totalitaire macht van de media) is het van belang na te denken over hoe we de verschillen tussen mensen overeind kunnen houden. Kunst kan daar steun bieden en dat is precies wat Whitman wil.   

Om jezelf als persoon te zien, is het nodig jezelf te zien als iemand met een eigen geest. Je moet jezelf kunnen zien, jouw eigen gedachten en gevoelens herkennen en weten dat je in de tijd en de ruimte leeft. Kortom, er is een zelfbewustzijn nodig van ik besta, neem waar, denk en voel en ik leef in de wereld. Dat is nodig ook om voorstellingen te maken van anderen in andere omstandigheden en de wereld buiten jezelf. Taal (om jezelf en elkaar te begrijpen) is daarbij nodig evenals een verantwoordelijkheidsgevoel daarvoor nodig is. Met taal en dat verantwoordelijkheidsgevoel is er een betere wereld mogelijk en dat geeft hoop. De hoop op de betere wereld en daaraan werken drukt Whitman uit in democratie, dat voor hem vooral de verbondenheid tussen mensen uitdrukt. Democratie omvat voor hem veel meer dan verkiezingen en politieke en partij-beslommeringen. Het gaat hem om de omgang en de interactie tussen mensen en de manier waarop we overtuigingen delen met elkaar in het openbare en persoonlijke leven. Het gaat Whitman om de mens, zijn karakter en zijn persoonlijkheid en om de omgang met elkaar. De individuele mens ziet hij als bouwsteen voor de democratie en elke steen hebben we daarvoor nodig. Te veel wil Whitman er ook weer niet over kwijt, want hij wil zich niet opdringen. Dan trekt hij zich terug en laat het aan de toekomstige generatie over:

>Wat mij aangaat; ik schrijf slechts een paar richtlijnen voor 
  de toekomst.
Ik doe slechts even en stap naar voren om me dan weer 
  terug te haasten in de duisternis.   

\
\
Bakker heeft een mooi boek geschreven over *Grasbladen* van Walt Whitman en daarin plaatst en bespreekt hij dit werk als filosoof. Aan de 19e -eeuwse tijd en context waarin Whitman opgroeit, besteedt Bakker betrekkelijk weinig aandacht. Voor mij had dit meer aandacht verdient. Bakker wisselt hoofdstuk over het poëziewerk Grasbladen af met hoofstukken over filosofische thema’s. Hij bespreekt die thema’s van de 19e -eeuwse Whitman vanuit de ooghoeken van 20ste/21ste-eeuwse filosofen. Meer nog dan het hoofdwerk zelf (waar hij terecht enorme bewondering voor heeft), lijkt het hem te gaan om de betekenis van dat werk voor onze tijd. Over integrale geletterdheid en burgerraden en dergelijke had Whitman het niet en daarmee wil ik maar flauw zeggen dat niet alles voortkomt uit het werk van Whitman. Bakker gebruikt Whitman vooral als inspiratiebron. Het gaat Bakker om de kracht van gras en hij wil dat het Whitmans poëziewerk stimulerend werkt op de kracht van de democratische samenleving en de progressieve politiek.     
Het is Richard Rorty, die vijfentwintig jaar geleden wijst op het humanistisch elan van de dichter Whitman en ook op het wetenschappelijke werk van zijn evenknie en de iets jongere John Dewey. Whitman en Dewey schrijven beiden op hun eigen manieren (de een met gevoel, de ander met theorie) veel over ervaring, communicatie, participatie en gemeenschap. Rorty ziet dat in de tijd van zijn pleidooi de sociaaleconomische strijd voor gelijkheid en sociale rechtvaardigheid en het werken aan een betere wereld worden ingeleverd voor cultuurpolitiek en getheoretiseer. Daarmee neemt links ten onrechte afstand van de erfenis van Whitman en Dewey. Bakker bouwt hierop voort. Allicht, zo denkt Bakker, kunnen we met Whitmans *Grasbladen* zelf weer meer zachtaardig, eenvoudig, kritisch, tolerant en vrijgevig worden en tegelijk het vertrouwen terugkrijgen in de democratische samenleving. Gras staat symbool voor overleving, volharding, diversiteit, verbinding, groei en sterfelijkheid en het is iets alledaags en onuitroeibaar. Door *Grasbladen* te bespreken, er de kracht van te laten zien en het in onze tijd te plaatsen stuurt Bakker ons naar een samenleving en een politiek waarin het om het individu, de persoon, de wereld en de kosmos gaat, het geheel en in samenhang. Minder belangrijk zijn voor hem politieke en sociale kwantiteit, belangrijker vindt hij de spirituele kwaliteit. Daar bedoelt hij mee dat we in ieder geval erkennen dat Iedereen anders, uniek en van waarde is. Daar bedoelt hij ook mee dat we weer uitstralen dat eigenlijk niemand het alleen kan doen. Iedereen is verbonden met andere mensen. Die andere mensen hebben we net zo goed als instituten nodig om te groeien en te bloeien. Laten we afstand nemen, zo straalt zijn boek uit, van ons egoïsme en onze zelfingenomenheid en onszelf bejubelen op de manier zoals Whitman dit voor ogen had, ook al staat dit heel ver af van wat we dagelijks om ons heen horen, zien en ervaren: “*Dit is wat je moet doen: heb de aarde en de zon en de dieren lief, veracht de rijken, geef een aalmoes aan iedereen die erom vraagt, sta op voor de dommen en dwazen, wijd je inkomen en arbeid aan anderen, haat tirannen, twist niet over God, bejegen gewone mensen geduldig en coulant, neem voor niets en niemand je hoed af, ga vrijelijk om met krachtige, onopgeleide mannen en vrouwen en met jongens en meisjes en met de moeders van gezinnen, lees deze bladen in de open lucht elk seizoen elk jaar van je leven, onderzoek opnieuw wat je op school of in de kerk of in de boeken verteld is, verwerp alles wat je besmet, en je bloedeigen vlees zal een groot gedicht zijn, en niet alleen rijkelijk vloeien in je woorden, maar ook in de stille welving van je lippen en je gezicht en tussen de wimpers van je ogen in alle bewegingen en gewrichten van je lichaam (p. 22)*”
\
\
Bakker, J.-H.(2024). *De kracht van gras. Walt Whitman en onze tijd*. Leusden: ISVW Uitgevers. 230 pagina’s.

## De evolutietheorie in het beklaagdenbankje
\
*De wet komt voort uit de wanhoop van de menselijke natuur* \
-   José Ortega Y Gasset
\
\
In de twintigste eeuw kent Amerika enkele bekende processen. Het Brown v. Board of Education-proces (1954) is er zo één. Het is aangespannen door Oliver Brown en anderen en gericht tegen het onderwijsbestuur van Topeka, Kansas. Inzet van dat proces is de rassenscheiding in het openbaar onderwijs. Met de uitspraak komt daar officieel een einde aan en zal belangrijk zijn voor de verdere ontwikkeling van de burgerrechten in het land. Een andere bekende zaak is de O.J. Simpson moordzaak, veertig jaar later, die uitloopt op een gigantisch mediaspektakel. Hier wordt de Amerikaanse voetbalspeler en auteur O.J. Simpson verdacht van moord op zijn ex-vrouw en haar nieuwe vriend. O.J. wordt eerst vrijgesproken van moord, maar later toch aansprakelijk gesteld voor doodslag. De bekendste rechtszaak van de 20ste eeuw is echter het ‘apenproces’ waarin een leraar (John T. Scopes) wordt beschuldigd van het onderwijzen van de nieuwe evolutietheorie, dat volgens de wetgeving van de staat Tennessee helemaal niet mag. Het gebeuren speelt zich af in de hete zomer van 1925 in het slaperig stadje Dayton, aan de voet van Cumberland-bergen ergens tussen Chattanooga en Knoxville; iedereen moet op de landkaart opzoeken waar het ligt. Hier wordt die zomer een nationale strijd gevoerd tussen religie en wetenschap, hier gaat het over God en de democratie. Twee partijen staan er recht tegenover elkaar en de één denkt heel anders over cultuur, ethiek, religie en de rol van de staat dan de ander. Via de radio kunnen Amerikanen de gebeurtenis volgen (dat is nieuw) en honderden journalisten zijn erbij in dat stadje om er verslag van te doen. Daar waar Amerika op allerlei manieren vernieuwt en innoveert, weet het helemaal niet goed waar het zelf in moet geloven. Het proces nagelt de hele natie een tijdlang vast.
\
\
Begin 1925 neemt de staat Tennessee met ruime meerderheid een wet aan die het verbiedt om elke theorie te onderwijzen die de Goddelijke Creatie ontkent zoals in de Bijbel verwoordt. Ook is het strafbaar te beweren dat wij mensen afstammen van de dieren. Het is duidelijk dat de Butler Act, zoals die wet heet, bedoeld is om het geloof in God te verdedigen en de verspreiding van de evolutietheorie een halt toe te roepen. Onderwijzers mogen in ieder geval vanaf nu de evolutietheorie niet meer onderwijzen in het openbaar onderwijs, noch in de colleges. In 1859 had Darwin zijn *Origins of Species* gepubliceerd. Daarin stelt hij dat soorten zich over lange tijd ontwikkelen via natuurlijke selectie. Individuen met gunstige eigenschappen hebben een grotere kans te overleven en zich voort te planten. Zo worden eigenschappen aan volgende generaties doorgegeven en dat weer kan leiden tot geleidelijke aanpassing van soorten aan hun omgeving. Darwin maakt duidelijk dat de wereld niet statisch is, maar verdurend verandert en ook dat we niet meer op een vaste manier tegen hiërarchie aan kunnen kijken. Misschien is het niet eens de evolutietheorie zelf, maar vooral het idee dat wij mensen van apen afstammen dat er bij de Fundamentalisten en de strenge Protestanten niet ingaat. Kinderen en jongeren op school en in de colleges mogen met die gedachten niet vergiftigd worden. De meer liberale protestanten daarentegen verdedigden juist dit nieuwe wetenschappelijke inzicht. Met de nieuwe wetgeving is de vrijheid van meningsuiting en de vrijheid om iets te leren in het geding. De American Civil Liberties Union, die het aan de kant staat van het meer vrije denken, voelt zich uitgedaagd door de nieuwe wetgeving en gaat op zoek gaat naar een leraar die het aandurft om de wet te overtreden. Er wordt een advertentie geplaatst in de plaatselijke krant en al snel reageert de jonge natuur- en wiskunde leraar John Thomas Scopes hierop. Hij durft het wel aan het onderwerp in de klas te behandelen. Hij geeft een biologieles uit het erkende boek *Civic Biology*, dat in een korte sectie dit onderwerp behandelt. Hij daagt de overheid uit en zo komt er in de zomer van 2025 dat bekende ‘apenproces’ hierover. 

In het boek maken we uitgebreid kennis met de belangrijke spelers in dit ware theaterstuk. In ieder geval is er een belangrijke rol weggelegd voor twee hoofdrolspelers. De liberale kant wordt vertegenwoordigd door de bekende jurist Charles Darrow. Voor Darrow is het duidelijk dat wetgeving iets is van mensenhanden. Wat we in deze wereld nodig hebben, is een beetje meer menselijkheid, denkt hij. In de aanloop naar het proces heeft Darrow al naam gemaakt in verschillende andere processen waarin hij steeds opkomt voor de armen, de achtergestelden en delen van de zwarte bevolking. Darrow verdedigt de arbeiders en de vakbond in bijvoorbeeld de Pullmann-staking van Chicago en ook de jongens Leopold en Loeb, die een veertienjarige jongen hebben vermoord. Hij weet dat de wetgeving vaak niet ver genoeg gaat om iedereen te beschermen en ziet daar een rol voor zichzelf om die op te rekken. Hij wil een bijdrage leveren aan de vernieuwing van wetgeving en het denken over criminaliteit. Darrow heeft niets tegen religie, integendeel, want een beetje religie hebben we volgens hem in het leven nodig. Hem gaat het om de burgerlijke vrijheden, de vrijheid om te zeggen en te denken wat je wilt en om de scheiding van kerk en staat. Recht tegenover Darrow staat de andere hoofdrolspeler, de populist en fundamentalist William Jennings Bryan, die in het boek het meest uitgebreid wordt beschreven. Hij is een bekende politicus voor de democratische partij (waar Darrow ook lid van is). Drie keer wordt Bryant genomineerd als democratische presidentskandidaat voor de landelijke verkiezing. Steeds verliest hij. Hij heeft wel een belangrijke positie onder Woodrow Wilson en wordt gezien als architect van de Volkenbond. Bryant komt als politicus op voor de mannen en vrouwen uit de kleine steden, van de boeren ook, van hen die niet gezien worden. Hij is net als Darrow voor de arbeiders, maar wel tegen de vakbond. Hij is de politicus met een romantisch hart en een religieuze ziel, die vindt dat hij leeft in de grootste tijd, het grootste land ooit en zich er bewust van is deel uit te maken van grootste ras ooit, het Kaukasische (blanke) ras. Bryant verdedigt ook steeds de slavernij, want een zwart persoon is uiteindelijk beter af met een blanke meester. Deze standpunten verdedigt hij ook in zijn eigen krant *The Commoner*, zoals hijzelf ook genoemd wordt. Hij had in Amerika nogal wat strijd geleverd en wil dit keer in dit proces de nieuwe wetgeving in Tennessee verdedigen. Want hij moet niets weten van Darwin ‘die ons niet eens laat afstammen van een goede Amerikaanse aap, hij laat ons van een Afrikaanse bruut afstammen’, net zo hij niets moet weten van het onderwijzen van ‘Darwinisme, atheïsme, agnostisme of de evolutietheorie in zoverre het de oorsprong van het leven betreft’. Een derde hoofdrolspeler, minder prominent en uitgewerkt in het boek, is Henry L. Mencken, een intellectuele journalist uit Baltimore die uitgebreid over het proces rapporteert waarvan Wineapple veel gebruik maakt in haar boek. Het is Mencken die de evolutietheorie via Thomas Henry Huxley in Amerika populariseert. Mencken is het eens met Huxley dat er alleen over evolutie kan worden nagedacht wanneer die met logische bewijsvoering wordt onderbouwd. Het is ook Mencken die voor het eerst heeft over het ‘apenproces’. Het is ook Mencken die Nietzsche voor Amerika ontdekt, die de Fundamentalisten dan weer op een hoop gooiden met Darwin. Er doen nog veel andere spelers mee in dit grote theaterstuk en hun rol wordt kort beschreven.     

Op 10 juli 2025 begint het proces, dat in het tweede deel van het boek van dag tot dag is te volgen. De verdediging maakt direct duidelijk dat wetenschap en religie twee hele verschillende werelden van denken en leren zijn en dat ze niet met elkaar verward moeten worden. Het is goed om te begrijpen dat ‘Moses nog nooit van stoom, elektriciteit, de telegraaf, de telefoon, het vliegtuig en boerenmachinerie gehoord had’. En Bryant, de ‘fundamentalistische paus’, zoals Mencken hem noem, verdedigt de letterlijke interpretatie van de bijbel en zijn superieure geloof. Hij wil voorkomen dat God de wereld uit wordt geschopt samen met onze morele standaarden, waarvoor we de verderfelijke Nietzsche en Darwin in de plaats krijgen. Het is niets voor niets, zo houdt hij voor, dat Nietzsche als gek is gestorven, hij maakt anderen ook gek en die malle evolutietheorie van Darwin draagt daaraan bij. Vooral de ondervraging van getuige Bryant door Darrow maakt indruk en van de grote Bryant blijft niet veel over. Scopes wordt toch veroordeeld voor het overtreden van de wetgeving met een boete en dat kon ook niet anders met deze rechter, deze juryleden in deze tijd.
\
\
Het boek van Wineapple is een hele mooie beschrijving van de tijd waarin het nieuwe Amerika aan het begin van de twintigste eeuw vorm krijgt. Elk land heeft verhalen nodig waarmee je het beter begrijpt. Dit verhaal over het ‘apenproces’ is zo’n verhaal. Het maakt duidelijk wat er zoal speelt en hoe er gedacht wordt. Wineapple maakt duidelijk dat vrouwen dan wel kiesrecht hebben gekregen, maar ze staan buiten het maatschappelijke gebeuren (behalve dat ze het proces mogen verslaan). De Eerste Wereldoorlog, waar Amerika halverwege 1917 aan mee doet, zorgt ervoor dat niets en niemand meer veilig is. Bekende personen worden van rode sympathieën verdacht, de Klu Klux Klan paradeert door de straten en zwarte Amerikanen worden gelyncht. Wineapple laat zien wat er tegelijk in de politiek gebeurt Zoals gezegd, Amerika vernieuwt en innoveert, maar weet niet goed wat het met zichzelf aan moet. Het is allemaal nog voordat er in Amerika een maatschappelijke consensus wordt gevonden met een balans tussen de behoeften van de burgers en de ondersteuning door de overheid. De invloed van Roosevelt, Dewey en Keynes moet zich nog laten gelden. Wineapple besteedt alle aandacht aan die beschrijving van de tijd voor die consensus en aan het begin van de modernisering. Ze trekt geen lijn naar het heden en de toekomst en laat dit aan de lezer over. Dat is trouwens wel wat er wat mij betreft aan ontbreekt in dit boek. Er is tegenwoordig opnieuw sprake van een sterke onderliggende strijd en boeken worden opnieuw verboden op scholen en colleges in verschillende staten van Amerika. Hoever dat verleden soms in de beschrijving ook lijkt te zijn, met de kern van het verhaal heeft het land ook nu weer te maken. Dit verhaal van honderd jaar geleden over het ‘apenproces’ leert ons beel over het land nu.
\
\
Wineapple, B. (2024). *Keeping the Faith. God, Democracy, and the Trial That Reveted a Nation*. New York: Random House. 511 pagina’s.

## Vrijheid als het leven zelf

\
*Kies in de strijd tussen jou en de wereld de zijde van de wereld*\
- Franz Kafka
\
\
Timothy Snyder is hoogleraar geschiedenis aan de Yale Universiteit (New Haven, VS). Zijn terrein is de geschiedenis van Oost- en Midden-Europa, Rusland en de Holocaust. Hij promoveerde bij Timothy Garton Ash (Oxford, Engeland), werkte op verschillende instituten in Europa (o.a. in Leiden) en schreef enkele populaire boeken. *Bloedlanden*(2010/2011) schreef hij bijvoorbeeld, dat gaat over hoe de nazi’s en de Sovjets massamoord inzetten als politiek beleid. In 2013 hielp hij Tony Judt bij het maken van *Denken over de twintigste eeuw* (toen Tony Judt door een spierziekte zelf niet meer kon schrijven). Kort na de Amerikaanse verkiezingen in 2016 schreef hij *Over tirannie* (2017), met twintig historische lessen die van belang zijn wanneer democratie wordt bedreigd.  Hij schreef ook \*De weg naar onvrijheid\* (2019), dat over Rusland, Europa en Amerika en de nieuwe wereldorde gaat. Over het kwaad heeft hij zich regelmatig uitgelaten in studies en lezingen. Natuurlijk is hij na de inval van Rusland regelmatig in de Oekraïne. Juist in die omgeving van bombardementen en moorden voelt hij zich uitgedaagd om na te denken over de keerzijde van het kwaad: het goede, vrijheid. Wat betekent het eigenlijk als we over vrijheid praten en wat komt daarbij kijken? Voor Schnyder is het duidelijk dat vrijheid meer is dan ergens vrij van zijn of iets schadelijks wegnemen. Dat is negatieve vrijheid voor hem, veiligheid meer. We moeten meer doen dan voorkomen dat dingen kapot worden gemaakt. We moeten iets betekenen, maken, scheppen. Van vrijheid is geen sprake als er iets niet is, van vrijheid is sprake als iets wel aanwezig is. Als er structuren, instituten en perspectieven zijn die die mensen steunen, laten groeien en ontwikkelen, want vrijheid is iets positiefs.    

In zijn nieuwe boek *Over Vrijheid* werkt hij filosofische grondslagen uit waarop vrijheid wat hem betreft gestoeld moet worden: soevereiniteit, onvoorspelbaarheid, mobiliteit, feitelijkheid en solidariteit; de vijf vormen van vrijheid, zoals hij ze noemt. Het zijn deze vormen waar het om gaat bij vrijheid en het zijn deze ideeën die we naar voren moeten schuiven.
\
\
Vrijheid gaat allereerst over het lichaam. Soevereiniteit is daarom zijn eerste vorm van vrijheid. Dit deel krijgt als het goed is vooral in de kindertijd vorm. Het is de Duitse filosofe Edith Stein die op het verschil heeft gewezen van *Kôrper* en *Leib*. Bij het eerste gaat om iets en bij het tweede om iemand, het één is object en het ander is subject. *Körper* tel je en met *Leib* hou je rekening, zeg maar. Of, zoals Stein het zelf definieerde: ‘er kan een *Körper* bestaan zonder mij, maar er kan geen Leib zijn zonder mij’. Het waren de nazi’s eerder die anderen als *Körper* zien waardoor mensen van diverse groepen zichzelf ook niet meer kunnen zien en zo de belofte van de eigen vrijheid en hoop verloren gaat.   

Snyder is sterk beïnvloed door Europese intellectuelen als de Tsjecho-Slovaak Vaclav Havel en de Polen Adam Michnik en Leszek Kolakowski. Hun tegendraadse denken brengt hij samen onder de tweede vorm van vrijheid die hij onvoorspelbaarheid noemt. Zij hadden weinig op met de stijfburgerlijke fatsoensnormen van het communistische regime van voor 1989. Dat communisme, zo stelden ze, holt morele normen uit en is niks anders dan star conformisme, het is betekenisloos en zorgt voor een duistere wereld en onvrijheid. Alles daarin is voorspelbaar. Vrijheid vraagt echter vraagt juist onvoorspelbaarheid met z’n dromen, verlangens en oordelen, dat zo belangrijk is met name voor de jeugd. Voor deze intellectuelen gelden andere regels en eigenlijk alleen maar ‘de wet van het leven’. Het alternatief dat zij bieden is ‘in de waarheid leven’ (Havel), leven ‘alsof we vrij zijn’ (Michnik) of ‘dingen doen die niemand van ons verwacht’ (Kolakowski). Hen gaat het niet in de eerste plaats om hoe, maar om het waarom. Hen gaat het om het zoeken naar ‘de wereld van waarheid’, vrijheid dat meer is dan nut en iets dat eerder redelijk dan rationeel is.   

Mobiliteit is de derde vorm van vrijheid en voor Snyder gaat het hier om de uitdaging van de volwassenheid. Bij deze vorm van vrijheid gaat het om vaardig bewegen in ruimte en tijd op basis van menselijke waarden waarbij we gaandeweg onze verhalen maken, die aanpassen waar nodig en uiteindelijk bepalen. Het gaat hier om bewegen, ontmoeten en met elkaar communiceren. Het zwarte deel van de Amerikaanse bevolking kon dat lange tijd maar heel beperkt. Het Amerikaanse beeld van de van nature werkschuwe en criminele zwarte blijft maar in het hoofd zitten en de ongelofelijke aantallen zwarten die vastzitten in Amerikaanse gevangenissen beperkt de mobiliteit ook. Denk ook aan de grote ongelijkheid die afstand creëert en vrijheid beperkt of aan de oligarchen die niet alleen het grootste deel van de taart maar ook nog eens het mes in hun handen hebben. Niets hiervan is nieuw en geschiedenis kan ons hier veel leren.
  Vrijheid heeft ook met waarheid te maken en met feiten waarmee we ons bestaan begrijpen. De feitelijkheid is voor Snyder de vierde vorm van vrijheid. Met kennis moeten we ons leven tegemoet treden. Het is nodig te snappen wat het leven is, hoe het functioneert en in elkaar zit, wat daarin meespeelt, wat er wel en niet mogelijk is en waar we op kunnen en hebben in te zetten. Als we onze ogen voor die kennis sluiten wordt het heel gevaarlijk. Voor Snyder gaat het hierbij niet zozeer om de vraag wie we zijn, maar veelmeer om wat we moeten doen. Met goed onderbouwde kennis kunnen we nieuwe en meer duurzame evenwichten en levensvormen vinden en ons verhouden tot onze leefomgeving. Ook dit deel van vrijheid vraagt om inspanning. Het is meer dan vrijheid van meningsuiting en de mogelijkheid om jouw mening te uiten. Feitelijkheid vraagt ook om luisteren, inschikkelijkheid en toegang krijgen tot onderwijs, wetenschap en journalistiek. Het gaat er niet om dat je kunt onderbouwen wat jou het beste uitkomt, maar om wat er doelgericht en gezamenlijk te doen is iets met die inzichten.   

Vrij ben je nooit alleen, maar dat ben je met anderen. Vrijheid heeft daarom altijd met solidariteit te maken, de vijfde en laatste vrijheidsvorm die Snyder presenteert in *Over Vrijheid*. Hier gaat het om mensen samenbrengen want alles wat we zijn en kunnen, hebben we uiteindelijk aan anderen te danken. Daarom hebben we ook de verantwoordelijkheid voor anderen wat terug te doen. De wereld van de ‘vrije markt’ en het libertarisme is niet goed met dit gedeelde vrijheidsbegrip te verenigen. De wereld is veel meer dan een spel om rijkdom te vergaren en voor jezelf opkomen. De wereld is er voor ons allen en niet alleen voor een kleine groep rijken.
\
\
In de zomer van 1976 wordt in Amerika 200 jaar onafhankelijkheid gevierd. Schnyder is dan nog kind maar herinnert zich die warme familiedag nog heel goed. In de jaren tachtig gaat hij zich interesseren in het werk van Oost-Europese dissidenten en komt via een studentenbaantje 1989/1990 persoonlijk met hen in aanraking. Hij merkt daar dat de angst voor de Sovjet-Unie plaats maakt voor overmoed en een vreemd soort vertrouwen in de toekomst. Hij wil hier meer van weten en gaat geschiedenis studeren. Nu weet hij daar meer over te zeggen en vervolgens komen er ook nog de rassenrellen, de Irak-oorlog en de financiële crises. Terugkijkend stelt hij vast dat het denken in positieve vrijheid plaats heeft gemaakt voor het denken in negatieve vrijheid. Hij wil dat we onszelf weer zien staan en daar een mening over durven te formuleren. Zijn vormen van vrijheid zijn de kern van zijn boek en geven structuur en richting aan zijn denken over vrijheid. In het laatste deel van het boek wordt hij concreter en laat hij zien wat we kunnen doen door anderen te helpen en zo ons zelf leren te begrijpen; door mensen te ontmoeten, te lezen, onze eigen levensweg te kiezen, lokaal en onafhankelijk nieuws te volgen en, bijvoorbeeld, deel te nemen aan maatschappelijk overleg of lid te worden van een belangenorganisatie. Het is nodig weer zelf te denken in plaats van gehoorzaam volgen wat algoritmes ons opleggen. Democratie is wat hem betreft een werkwoord en een waardeoriëntatie die verbeterd kan worden. Het werkt alleen als de representatie een eerlijke afspiegeling is van alle mensen en een kleine groep het niet met geld kan afkopen of opleggen. Hij laat zien wat vrijheid voor kinderen, ouders, werknemers en gevangenen betekent. Daar bovenop is het nodig democratieën elders te verdedigen, ongelijkheden in eigen land terug te brengen en voor onze natuur te zorgen. Vrijheid heeft ook met ons dagelijks leven te maken, waarin we meer van het scherm los zouden moeten komen om rustig te kunnen ademen, vriendelijk en redelijk te zien, beter te kunnen luisteren en zelf kunnen nadenken.   

Het duurt even voordat je in het verhaal van Schnyder zit. In dit boek reist hij met de lezer door de moderne geschiedenis, laat hij je kennis maken met personen die hierbij van belang zijn en deelt hij ervaringen. Elementen trouwens die hij niet evenwichtig verdeelt over de hoofdstukken: in de eerste hoofdstukken krijgen personen die hem geïnspireerd hebben meer plek dan in latere hoofdstuk. *Over Vrijheid* is een indrukwekkend boek om te lezen in de tijd van de inauguratie van de president van Amerika en er nogal wat gebeurt in de wereld. Ondertussen lijkt dit zelf wel een dissident geluid te zijn geworden nu heel anders over hoe het is en het zou moeten worden wordt gedacht. Die ruimte die Schnyder zo graag met zijn vrijheidsvormen vult is ondertussen door anderen bezet. Over waar het in de ruimte volgens Schnyder om moet gaan is heel duidelijk, minder duidelijk is hij over hoe de ruimte met deze democratische ideeën is te bezetten. De vraag die hier open blijft staan is: hoe kunnen we ons weer in deze wereld thuis voelen, dit soort doeleinden formuleren en deze ook nog tot stand brengen?
\
\
Snyder, T. B. (2024). *Over Vrijheid*. Amsterdam: Uitgeverij Balans. 454 pagina’s.